### ISSUE TITLE
Test on more sample dataframes

### ISSUE THREAD

**Issue by paddymul** [buckaroo-data/buckaroo#100]
Look at https://mwouts.github.io/itables/sample_dataframes.html
Code here https://github.com/mwouts/itables/blob/main/itables/sample_dfs.py

Particularly the duplicated column names example.

Start with posting in this issue thread  just the code for each one and a picture of the rendering

Make sure you have upgraded to Buckaroo 0.4.0

Here is the code for the first one.
```
from itables.sample_dfs import get_dict_of_test_dfs
dict_of_test_dfs = get_dict_of_test_dfs()
dict_of_test_dfs["empty"]
```

**Comment by Omkar-23** [comment]
@paddymul, could you please provide more information about this issue? I'm new to open source, but I'm eager to help resolve it.

**Comment by paddymul** [comment]
Thank you for your interest.

Take a look at this closed bug
https://github.com/paddymul/buckaroo/issues/89

Can you follow the links in the first comment and try some of those dataframes in buckaroo?  ITables is another jupyter library that has tried a bunch of different types of DataFrames.  Frequently there are weird DataFrames that don't display properly in Buckaroo.

I will do an example below.

**Comment by paddymul** [comment]
@Omkar-23 I tried the first sample and it resulted in an error.  Here is the bug report https://github.com/paddymul/buckaroo/issues/102

**Comment by Omkar-23** [comment]
Should I proceed with executing the tests from `https://mwouts.github.io/itables/sample_dataframes.html` and provide the results here? Please excuse me if I'm being too inquisitive and demanding your attention.

**Comment by paddymul** [comment]
Please do.

**Comment by Omkar-23** [comment]
> Please do.

Thanks.. on it

**Comment by Omkar-23** [comment]
Hey!, @paddymul  I've gone ahead and executed almost all the data frames from `https://mwouts.github.io/itables/sample_dataframes.html`
and I wanted to double-check if the way I'm planning to present the results works for you.


*here's an example*
`show(dict_of_test_dfs["ordered_categories_in_multiindex"])`

![image](https://github.com/paddymul/buckaroo/assets/144553703/da7a9f75-b038-4b26-9b07-8b12cf2608fe)


Please correct me if any changes are necessary.

**Comment by paddymul** [comment]
Are you running that in VS Code?

The call to `show` is unnecesary.

Here is what I see:
<img width="597" alt="Screen Shot 2023-11-08 at 11 33 47 AM" src="https://github.com/paddymul/buckaroo/assets/40453/cbd82158-65eb-41f5-a0d4-31d068bef7e3">

**Comment by paddymul** [comment]
Please post pictures of the buckaroo rendering for each dataframe rendering.  

For that particular dataframe, here's my thoughts
1. Buckaroo displays something - good
2. Buckaroo doesn't separate out the distinct multi index columns. not great... but a known bug #104

**Comment by Omkar-23** [comment]
> Are you running that in VS Code?

I tried using Jupyter Notebook and started facing some local Kernal issues.. so I executed the tests on Google Collab

**Comment by ghost** [comment]
Where to create the issues in buckaroo repo or the itables repo?
