### ISSUE TITLE
Empty Dataframes don't display

### ISSUE THREAD

**Issue by paddymul** [buckaroo-data/buckaroo#102]
Based on ITables the following code doesn't show the UI
```
from itables.sample_dfs import get_dict_of_test_dfs
dict_of_test_dfs = get_dict_of_test_dfs()
dict_of_test_dfs["empty"]
```
<img width="1075" alt="Screen Shot 2023-11-07 at 1 03 36 PM" src="https://github.com/paddymul/buckaroo/assets/40453/f2c913df-6ab8-4d5e-bc76-b30cd30cac2a">

**Comment by nasrin1748** [comment]
.take

**Comment by ghost** [comment]
df = pd.DataFrame(columns=[]) 
Dataframe with no columns doesn't showup so Buckaroo doesn't showup.
