### ISSUE TITLE
Failed to load model Class 'DCEFWidgetModel' from Module 'buckaroo'

### ISSUE THREAD

**Issue by Haroldmut** [buckaroo-data/buckaroo#103]
I am getting an error while trying to run Buckaroo in JupyterLab. Here is the message I am getting (see below). How can I fix this? 

"""Failed to load model class 'DCEFWidgetModel' from module 'buckaroo'
Error: No version of module buckaroo is registered
at f.loadClass (https...)
at f.loadModelClass (https...) 
at f._make_model (https...)
at f.handle_comm_open (https...)"""

**Comment by paddymul** [comment]
can you please run
```
import buckaroo
buckaroo.debug_packages()
```
and paste the results.

Also try 
Menu > Kernel > Restart and Clear All Outputs
then
Menu > File > Save
then reload your browser and re-execute the cells.

I think that Jupyter hasn't properly loaded the JS.

**Comment by Haroldmut** [comment]
import buckaroo
buckaroo.debug_packages()

Selected Jupyter core packages...
buckaroo not installed
jupyterlab 0.35.6
notebook 6.1.4
ipywidgets 7.6.3
jupyter_core 5.0.0
tornado 5.1.1
traitlets 5.0.5
ipykernel 5.5.5
jupyter_client 6.1.12
nbconvert 5.6.1
nbformat 5.0.8
qtconsole 4.7.7

/apps/vals/services/jupyter-notebook/latest/jhub-py39/lib/python3.9/site-packages/buckaroo/__init__.py
/apps/vals/services/jupyter-notebook/latest/jhub-py39/lib/python3.9/site-packages/jupyterlab/__init__.py
/apps/vals/services/jupyter-notebook/latest/jhub-py39/lib/python3.9/site-packages/notebook/__init__.py
/apps/vals/services/jupyter-notebook/latest/jhub-py39/lib/python3.9/site-packages/ipywidgets/__init__.py
/apps/vals/services/jupyter-notebook/latest/jhub-py39/lib/python3.9/site-packages/jupyter_core/__init__.py
/apps/vals/services/jupyter-notebook/latest/jhub-py39/lib/python3.9/site-packages/tornado/__init__.py
/apps/vals/services/jupyter-notebook/latest/jhub-py39/lib/python3.9/site-packages/traitlets/__init__.py
/apps/vals/services/jupyter-notebook/latest/jhub-py39/lib/python3.9/site-packages/ipykernel/__init__.py
/apps/vals/services/jupyter-notebook/latest/jhub-py39/lib/python3.9/site-packages/jupyter_client/__init__.py
/apps/vals/services/jupyter-notebook/latest/jhub-py39/lib/python3.9/site-packages/nbconvert/__init__.py
/apps/vals/services/jupyter-notebook/latest/jhub-py39/lib/python3.9/site-packages/nbformat/__init__.py
/apps/vals/services/jupyter-notebook/latest/jhub-py39/lib/python3.9/site-packages/qtconsole/__init__.py

**Comment by Haroldmut** [comment]
getting the same error even after the steps suggested above

**Comment by paddymul** [comment]
It looks like you are on a very old version of Jupyter Lab, 0.35.6 
Also your notebook version is 6.0

Please upgrade to jupyter lab 3.6.0 or greater

I need to fix the package.toml per this bug https://github.com/paddymul/buckaroo/issues/65

Also if you just want to try out buckaroo, try  this google colab link
https://colab.research.google.com/github/paddymul/buckaroo/blob/chore/colab-play/example-notebooks/Full-tour.ipynb

**Comment by paddymul** [comment]
#duplicate 65

**Comment by paddymul** [comment]
Thanks for giving buckaroo a try!

Sorry the initial install experience left you with these bugs.

The reports are really helpful for polishing buckaroo in different environments.

**Comment by nrenzoni** [comment]
I had just installed backaroo for the first time and was getting the same error:

`Failed to load model class 'DCEFWidgetModel' from module 'buckaroo'`

Restarting the python kernel didn't cause the error to go away. After restarting my jupyter server though, the error did go away. 

@paddymul maybe add that Jupyter needs to be restarted for backaroo to run properly?

Thanks for a great project!

**Comment by paddymul** [comment]
This is a bug with Jupyter. But it looks like a buckaroo bug.  The error is thrown from javascript, so I don't think I can injecrt any javascript to test for the conditions... (but maybe I can).

The other thing I could do is check the MTIME on the buckaroo package and the uptime on the jupyter server (somehow???), compare them.  If the buckaroo package was installed after the jupyter server was started, then throw an error from python (which does reliably install and run), exlain to the user that they need to restart the jupyter server.

I'm aware of bugs around this, but they tend to happen infrequently.  For pushing adoption my biggeest problem is top of the funnel (awareness) as opposed to people getting a loading error and giving up.
