### ISSUE TITLE
"no_rows_one_column" is showing  two columns.

### ISSUE THREAD

**Issue by ghost** [buckaroo-data/buckaroo#107]
show(dict_of_test_dfs["no_rows"])-i.e no row with one column.
show(dict_of_test_dfs["no_rows_one_column"])-i.e no row with one column.
should show same result but showing different result
<img width="600" alt="9" src="https://github.com/paddymul/buckaroo/assets/79505893/d02b38d5-0182-4ab6-aac4-02a6068a3ee5">
<img width="566" alt="10" src="https://github.com/paddymul/buckaroo/assets/79505893/314ec008-7ff9-42fd-ade1-1b6e35473c9a">

**Comment by paddymul** [comment]
You're showing ITables rendering, not buckaroo rendering.  I can look at the page in ITables docs to see their rendering

**Comment by ghost** [comment]
buckaroo rendering shows the correct result.
