### ISSUE TITLE
infinity and nan are not displayed.

### ISSUE THREAD

**Issue by ghost** [buckaroo-data/buckaroo#117]
<img width="222" alt="11" src="https://github.com/paddymul/buckaroo/assets/79505893/6fab2f78-03f5-4d06-8f49-d4b0171487b3">
<img width="594" alt="12" src="https://github.com/paddymul/buckaroo/assets/79505893/996b9734-1a76-4f35-86cc-b8a8028b21b6">

**Comment by paddymul** [comment]
I rewrote this as #122 (which is now the example bug report in the template.
