### ISSUE TITLE
Buckaroo 0.4.8 rendering issue

### ISSUE THREAD

**Issue by ghost** [buckaroo-data/buckaroo#186]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/paddymul/buckaroo) of Buckaroo.

### What type of jupyter notebook were you using (VSCode notebook, google colab, Jupyter Lab, Jupyter notebook).  Select multiple if you can reproduce this in multiple environments.  If other, please add to description.

Jupyter Lab

### Reproducible example

Trying to print dataframe with buckaroo rendering throws javascript error for buckaroo 0.4.8 version.
```python
import pandas as pd
df = pd.DataFrame(
    dict(Names=[10,10]))
df
```
**Jupyter Log output**

<img width="72" alt="22" src="https://github.com/paddymul/buckaroo/assets/79505893/cfdbbfb9-b2bf-4b5d-b84c-764921fa9604">

### Issue description

<img width="605" alt="15" src="https://github.com/paddymul/buckaroo/assets/79505893/b25006b5-384a-43ca-9dfe-cdc3d3aa8840">
<img width="602" alt="16" src="https://github.com/paddymul/buckaroo/assets/79505893/e8cad462-c74f-4749-a5c8-69b8eddfda42">

### Expected behavior

Display dataframe with buckaroo rendering.

### Installed versions

<details>
```
buckaroo 0.4.8
```
</details>

**Comment by paddymul** [comment]
Please run `buckaroo.debug_packages()` This will show all of the relevant buckaroo packages.  There is also new code to show the notebook environment.

**Comment by ghost** [comment]
Did'nt upgrade the standard notebook to >7.
