### ISSUE TITLE
Support html-linkification of string type column display

### ISSUE THREAD

**Issue by mdrcode** [buckaroo-data/buckaroo#194]
### Checks

- [X] I have checked that this enhancement has not already been requested

### How would you categorize this request.  You can select multiple if not sure

Display (is this related to visual display of a value), Developer ergonomics (defaults, error messages)

### Enhancement Description

* Support a "hint" mechanism so the caller can indicate that a string-type column contains URLs
* Then render those URLs to be clickable ("linkified") within the table if possible
* Fail gracefully if a cell's contents are not trivially linkable

Probably this depends on #190 being implemented. One might argue that full html support via #190 makes this issue redundant, but I think "link-ification" is a sufficiently common and simple use case that a convenience helper might be merited. Similar to how Google Spreadsheets will automatically link-ify a column if it detects URLs.

Perhaps instead of (or in addition to) exposing this functionality via API hint, it could be entirely hosted within the UI: such as clicking on a column header, or right clicking on a column, and selecting "Linkify".

BTW - this is awesome software, thank you!

### Prior Art

<img width="747" alt="image" src="https://github.com/paddymul/buckaroo/assets/56870/70ab9bdd-8e22-44ba-9405-ff24a7a6a3f7">

**Comment by paddymul** [comment]
Thanks for your interest.  I'm trying to finish up the polars backend at this point, then I will be switching back to some TS/frontend dev.

I'm a little concerned about the security implications of HTML and linkification.  My personal primary usecase for buckaroo is looking at completely unknown datasets and making sense of them.  For this usecase (and the default config) I want to be conservative.

I need to figure out some better ways to configure buckaroo for features like HTML/linkification.  What would you want that experience to look like, from the python side?  Would you mind writing some pseudocode sketches?  I'd be up for a screenshare pair on this topic too.

**Comment by ghost** [comment]
Does it apply for image links as well?
<img width="626" alt="27" src="https://github.com/paddymul/buckaroo/assets/79505893/5b505d98-0ed2-46fa-bed6-30167c500d8f">

**Comment by paddymul** [comment]
@mdrcode I have a frontend prototype for this.
<img width="386" alt="Screenshot 2023-12-22 at 6 08 22 PM" src="https://github.com/paddymul/buckaroo/assets/40453/50d7ced7-b7dd-43c9-8e77-1644cff1d5e2">

Any comments?
The blue on black is a bit hard to see.  I'm very open to color and styling suggestions.

This feature will be coming out with https://github.com/paddymul/buckaroo/pull/201 ... which will bump buckaroo to 0.6
aiming for early January,  need to find time during the holidays.

**Comment by paddymul** [comment]
@nasrin1748 I don't intend to support rendering random html as seen in that flag example.  It seems a bit freeform and opens up security and rendering bugs.

**Comment by ghost** [comment]
Buckaroo seems to avoid things which are dependent on w3.

**Comment by paddymul** [comment]
@mdrcode I haven't forgotten about this.  The upcoming 0.6 release adds a `linkify` method of styling for columns.  Here is an early demo video of styling 
https://www.youtube.com/watch?v=cbwJyo_PzKY

**Comment by ghost** [comment]
Great job @paddymul. Lot of changes happened to buckaroo and I really like the way it looks now.

**Comment by mdrcode** [comment]
Thank you @paddymul this looks awesome. Apologize for radio silence from my side (my wife filed issue "third baby coming" against me with priority zero). I will check this out in the 0.6 release

**Comment by paddymul** [comment]
Fixed by #201 for release 0.6.1
