### ISSUE TITLE
Spaces within String.

### ISSUE THREAD

**Issue by ghost** [buckaroo-data/buckaroo#195]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/paddymul/buckaroo) of Buckaroo.

### What type of jupyter notebook were you using (VSCode notebook, google colab, Jupyter Lab, Jupyter notebook).  Select multiple if you can reproduce this in multiple environments.  If other, please add to description.

Jupyter Lab

### Reproducible example

```python
import pandas as pd
df = pd.DataFrame({'date': ['  10-1-2023', ' he l lo', '10   -6-2023', '10-6-   2023',
                            '10-   14-2023', '10-   15-2023', '10-29-2023'],
                   'time': ['4:  15:00', '7  :16:04', '9:  25:00', '10 :13 :45',
                            '15:  30:00', '18 :15:00', '23  :15:00']})
df
```

### Issue description

Buckaroo rendering should handle the spaces.
<img width="338" alt="13" src="https://github.com/paddymul/buckaroo/assets/79505893/c252c5da-a195-42ac-a6e7-45e66f61cef3">

### Expected behavior

<img width="440" alt="14" src="https://github.com/paddymul/buckaroo/assets/79505893/c332ab94-9ae3-434b-a4a4-31babdcd435a">

### Installed versions

<details>
```
buckaroo 0.4.8
```
</details>

**Comment by paddymul** [comment]
I can't reproduce this.
<img width="631" alt="Screenshot 2023-12-12 at 9 24 51 PM" src="https://github.com/paddymul/buckaroo/assets/40453/b4479c26-92f6-42f0-a120-477afb2cb3e2">
