### ISSUE TITLE
std(Standard deviation) for dataframe description.

### ISSUE THREAD

**Issue by ghost** [buckaroo-data/buckaroo#197]
### Checks

- [X] I have checked that this enhancement has not already been requested

### How would you categorize this request.  You can select multiple if not sure

Summary stats

### Enhancement Description

Buckaroo rendering Stats displays mean,mode but not the std(standard deviation).

### Prior Art

Helps to have a closer look at the data.

**Comment by paddymul** [comment]
Standard deviation isn't displayed by default.  It can be trivially computed and there are examples of adding summary stats in the docs.
