### ISSUE TITLE
Sort behaviour for datetime

### ISSUE THREAD

**Issue by ghost** [buckaroo-data/buckaroo#198]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/paddymul/buckaroo) of Buckaroo.

### What type of jupyter notebook were you using (VSCode notebook, google colab, Jupyter Lab, Jupyter notebook).  Select multiple if you can reproduce this in multiple environments.  If other, please add to description.

Jupyter Lab

### Reproducible example

```python
import pandas as pd
df = pd.DataFrame({'date': ['10-8-2023', '10-4-2023', '10-6-2023', '10-6-2023',
                            '10-14-2023', '10-15-2023', '10-29-2023'],
                   'time': ['4:15:00', '7:16:04', '9:25:00', '10:13:45',
                            '15:30:00', '18:15:00', '23:15:00']})
df

```
### Issue description

Sort (<img width="18" alt="123" src="https://github.com/paddymul/buckaroo/assets/79505893/cf9e2631-ffed-454a-b7ff-ab2635e88ab3">) (<img width="19" alt="22" src="https://github.com/paddymul/buckaroo/assets/79505893/c61b31c9-2209-427e-b0d9-f96d0a4265f4">)doesn't obey the rule of sorting datetime.
<img width="453" alt="21" src="https://github.com/paddymul/buckaroo/assets/79505893/5f4b7b4a-613e-4619-96f0-f869b30f56ba">

### Expected behavior

Sort (<img width="18" alt="123" src="https://github.com/paddymul/buckaroo/assets/79505893/cf9e2631-ffed-454a-b7ff-ab2635e88ab3">) Oldest to Newest datetime and Sort (<img width="19" alt="22" src="https://github.com/paddymul/buckaroo/assets/79505893/c61b31c9-2209-427e-b0d9-f96d0a4265f4">)Newest To Oldest datetime.

### Installed versions

<details>
```
Buckaroo 0.4.8
```
</details>

**Comment by paddymul** [comment]
I thought I had commented previously.

These aren't sorting as datettimes because the columns are being treated as strings, not timestamps.
try this:
```python
df = pd.DataFrame({'date': ['10-8-2023', '10-4-2023', '10-6-2023', '10-6-2023',
                            '10-14-2023', '10-15-2023', '10-29-2023'],
                   'time': ['4:15:00', '7:16:04', '9:25:00', '10:13:45',
                            '15:30:00', '18:15:00', '23:15:00']})
df['date'] = pd.to_datetime(df['date'])
```

**Comment by ghost** [comment]
They are sorted now but date with no time still takes @time 24:00:00. Should be 00:00:00.
Time with no date still takes @todays date. Should be 00-00-00. #177 
 
<img width="437" alt="13" src="https://github.com/paddymul/buckaroo/assets/79505893/12c49ab5-5efa-4dfe-ae4d-efab72d7eba7">
