### ISSUE TITLE
Splitting of String into multiple columns.

### ISSUE THREAD

**Issue by ghost** [buckaroo-data/buckaroo#204]
### Checks

- [X] I have checked that this enhancement has not already been requested

### How would you categorize this request.  You can select multiple if not sure

Auto Cleaning

### Enhancement Description

Buckaroo rendering should handle the split functionality for strings.

### Prior Art

Adding regex functionality.

**Comment by paddymul** [comment]
I don't even understand what you're asking for here.

**Comment by ghost** [comment]
I was asking for the following.  (https://saturncloud.io/blog/how-to-split-a-date-column-into-separate-day-month-year-columns-in-pandas/)
