### ISSUE TITLE
Double Index 

### ISSUE THREAD

**Issue by ghost** [buckaroo-data/buckaroo#209]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/paddymul/buckaroo) of Buckaroo.

### What type of jupyter notebook were you using (VSCode notebook, google colab, Jupyter Lab, Jupyter notebook).  Select multiple if you can reproduce this in multiple environments.  If other, please add to description.

Jupyter Notebook

### Reproducible example

I am trying to read a file which already has index column.Buckaroo rendering displays double index.
```python
import pandas as pd
import buckaroo 
df = pd.read_csv("read.txt", sep=",")
df
```

### Issue description

<img width="395" alt="8" src="https://github.com/paddymul/buckaroo/assets/79505893/31f16fc0-5207-49ef-8e74-5609b1baeb3f">

### Expected behavior

Single index should be displayed.

### Installed versions

<details>
```
Selected Jupyter core packages...
executing in jupyter-notebook 
buckaroo         : 0.5.0
jupyterlab       : 3.6.3
notebook         : 7.0.6
ipywidgets       : 8.1.1
traitlets        : 5.7.1
jupyter_core     : 5.3.0
pandas           : 2.0.3
numpy            : 1.26.0
IPython          : 8.12.0
ipykernel        : 6.25.0
jupyter_client   : 7.4.9
jupyter_server   : 1.24.0
nbclient         : 0.5.13
nbconvert        : 6.5.4
nbformat         : 5.9.2
qtconsole        : 5.4.2
buckaroo         : C:\Users\91949\anaconda\lib\site-packages\buckaroo\__init__.py
jupyterlab       : C:\Users\91949\anaconda\lib\site-packages\jupyterlab\__init__.py
notebook         : C:\Users\91949\anaconda\lib\site-packages\notebook\__init__.py
ipywidgets       : C:\Users\91949\anaconda\lib\site-packages\ipywidgets\__init__.py
traitlets        : C:\Users\91949\anaconda\lib\site-packages\traitlets\__init__.py
jupyter_core     : C:\Users\91949\anaconda\lib\site-packages\jupyter_core\__init__.py
pandas           : C:\Users\91949\anaconda\lib\site-packages\pandas\__init__.py
numpy            : C:\Users\91949\anaconda\lib\site-packages\numpy\__init__.py
IPython          : C:\Users\91949\anaconda\lib\site-packages\IPython\__init__.py
ipykernel        : C:\Users\91949\anaconda\lib\site-packages\ipykernel\__init__.py
jupyter_client   : C:\Users\91949\anaconda\lib\site-packages\jupyter_client\__init__.py
jupyter_server   : C:\Users\91949\anaconda\lib\site-packages\jupyter_server\__init__.py
nbclient         : C:\Users\91949\anaconda\lib\site-packages\nbclient\__init__.py
nbconvert        : C:\Users\91949\anaconda\lib\site-packages\nbconvert\__init__.py
nbformat         : C:\Users\91949\anaconda\lib\site-packages\nbformat\__init__.py
qtconsole        : C:\Users\91949\anaconda\lib\site-packages\qtconsole\__init__.py
```
</details>

**Comment by paddymul** [comment]
can you share the original csv file. or even better a dataframe resulting from that file.  That way I can reproduce the bug.

copy and paste the results of the following
```
small_df = df[:5] #only five rows are needed
small_df.to_json()
```

paste this as text into the bug report.

**Comment by ghost** [comment]
@paddymul  i was reading .txt file as .csv file.

[read.txt](https://github.com/paddymul/buckaroo/files/14052978/read.txt)

Even if i make changes in my .txt file it's reflecting  into the index column. As of what i know index should always be in series.

In the below fig i deleted index no.4 from my .txt and it reflected into index column.

<img width="395" alt="9" src="https://github.com/paddymul/buckaroo/assets/79505893/07253173-dd6a-4931-bfb0-6af2b7f9a642">

> '{"index":{"0":1,"1":2,"2":3,"3":5,"4":6},"User Id":{"0":"8717bbf45cCDbEe","1":"3d5AD30A4cD38ed","2":"810Ce0F276Badec","3":"9afFEafAe1CBBB9","4":"aF75e6dDEBC5b66"},"First Name":{"0":"Shelia","1":"Jo","2":"Sheryl","3":"Lindsey","4":"Sherry"},"Last Name":{"0":"Mahoney","1":"Rivers","2":"Lowery","3":"Rice","4":"Caldwell"},"Sex":{"0":"Male","1":"Female","2":"Female","3":"Female","4":"Male"},"Email":{"0":"pwarner@example.org","1":"fergusonkatherine@example.net","2":"fhoward@example.org","3":"elin@example.net","4":"kaitlin13@example.net"},"Phone":{"0":"857.139.8239","1":"+1-950-759-8687","2":"(599)782-0605","3":"(390)417-1635x3010","4":"8537800927"},"Date of birth":{"0":"2014-01-27","1":"1931-07-26","2":"2013-11-25","3":"1923-04-15","4":"1917-08-06"},"Job Title":{"0":"Probation officer","1":"Dancer","2":"Copy","3":"Biomedical engineer","4":"Higher education lecturer"}}'

The issue will follow up even for .csv and if the index name in .csv file is **index** i.e exact as Buckaroo rendering index name.

**Comment by paddymul** [comment]
The following code renders as such.  Arguably having two index columns was the correct behavior, so this might be a bug now.  

```python
raw_json = '''
{ "index":{"0":1,"1":2,"2":3,"3":5,"4":6},
  "User Id":{"0":"8717bbf45cCDbEe","1":"3d5AD30A4cD38ed","2":"810Ce0F276Badec","3":"9afFEafAe1CBBB9","4":"aF75e6dDEBC5b66"},
  "First Name":{"0":"Shelia","1":"Jo","2":"Sheryl","3":"Lindsey","4":"Sherry"},
  "Last Name":{"0":"Mahoney","1":"Rivers","2":"Lowery","3":"Rice","4":"Caldwell"},
  "Sex":{"0":"Male","1":"Female","2":"Female","3":"Female","4":"Male"},
  "Email":{"0":"pwarner@example.org","1":"fergusonkatherine@example.net","2":"fhoward@example.org","3":"elin@example.net","4":"kaitlin13@example.net"},
  "Phone":{"0":"857.139.8239","1":"+1-950-759-8687","2":"(599)782-0605","3":"(390)417-1635x3010","4":"8537800927"},
  "Date of birth":{"0":"2014-01-27","1":"1931-07-26","2":"2013-11-25","3":"1923-04-15","4":"1917-08-06"},
  "Job Title":{"0":"Probation officer","1":"Dancer","2":"Copy","3":"Biomedical engineer","4":"Higher education lecturer"}}'''
pd.read_json(raw_json)
```

<img width="1268" alt="Screenshot 2024-03-08 at 1 18 33 PM" src="https://github.com/paddymul/buckaroo/assets/40453/ea189c8f-d768-4780-9658-f7c05d2bbb7d">
