### ISSUE TITLE
Adding two numerical columns.

### ISSUE THREAD

**Issue by ghost** [buckaroo-data/buckaroo#217]
### Checks

- [X] I have checked that this enhancement has not already been requested

### How would you categorize this request.  You can select multiple if not sure

Auto Cleaning

### Enhancement Description

I really like this idea of adding but not sure it gets fitted into buckaroo or can use on a data frame.
https://www.freecodecamp.org/news/create-animations-in-react/

### Prior Art

https://www.freecodecamp.org/news/create-animations-in-react/

**Comment by paddymul** [comment]
This isn't in scope for buckaroo.  Buckaroo is meant to visualize dataframes and perform transformations on them.  It is not meant to "visualize transforms of dataframes"
