### ISSUE TITLE
Basic support for GeoPandas

### ISSUE THREAD

**Issue by paddymul** [buckaroo-data/buckaroo#223]
### Checks

- [X] I have checked that this enhancement has not already been requested

### How would you categorize this request.  You can select multiple if not sure

Display (is this related to visual display of a value), Other (please describe in Issue Description)

### Enhancement Description

Buckaroo currently throws an error when a GeoPandas dataframe is passed in.
https://colab.research.google.com/drive/17pTPsLt2BUZRNyJ__J13-nSNGJFd8P4G?usp=sharing#scrollTo=GRCjYN8Zi6BT

GeoPandas dataframes should have at a minimum
1. not throw a stack trace in buckaroo
2. display at least a text representation of Polygon and other types

Further improvements in approximate order of difficulty
1. Custom Styling setup for GEO Column types
2. support a google maps link for POINT
3. Build out base64 image renderer cell type and build a styler to call Matplotlib to render GeoTypes to base64 then use that renderer
4. google maps renderer

### Prior Art

n/a

**Comment by chbrandt** [comment]
This sounds very cool, but probably to much for "support". In particular, items 2-4 should be left to another library (or extension function).

I guess it would be enough and in accordance to what Buckaroo (already) does for categorical columns to display the histogram of geometry types in the GeoDataFrame. Take for example the output of `gdf.geometry.geom_type` in "Analysing GeoSeries" section in the notebook you linked above (`gdf.geometry.geom_type.value_counts().plot.bar()`):

![image](https://github.com/paddymul/buckaroo/assets/482051/8096838d-6f6a-42f6-b949-11a9074cd900)

This would be enough, I'd say.

**Comment by paddymul** [comment]
Fixed with release 0.6.5 and  Feat/svg renderer #250
