### ISSUE TITLE
Serialization error on GeoPandas

### ISSUE THREAD

**Issue by paddymul** [buckaroo-data/buckaroo#224]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/paddymul/buckaroo) of Buckaroo.

### What type of jupyter notebook were you using (VSCode notebook, google colab, Jupyter Lab, Jupyter notebook).  Select multiple if you can reproduce this in multiple environments.  If other, please add to description.

Jupyter Lab

### Reproducible example

```python
import geopandas
import requests
from buckaroo.buckaroo_widget import BuckarooWidget

geojson = requests.get('https://gist.githubusercontent.com/chbrandt/bb64d9a6fc00a89d7410e6db8d126dfe/raw/8bc7a45c57e1c701618c940525d83bee80fd6b90/africa.geojson')
assert 200 <= geojson.status_code < 400
geojson = geojson.json()
gdf = geopandas.GeoDataFrame.from_features(geojson)
BuckarooWidget(df=gdf)
```

### Issue description

Buckaroo throws a serialization stacktrace
```python-traceback
TypeError                                 Traceback (most recent call last)

[<ipython-input-14-f2184ee5035d>](https://localhost:8080/#) in <cell line: 1>()
----> 1 BuckarooWidget(df=gdf)

15 frames

[/usr/lib/python3.10/json/__init__.py](https://localhost:8080/#) in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
    232     if cls is None:
    233         cls = JSONEncoder
--> 234     return cls(
    235         skipkeys=skipkeys, ensure_ascii=ensure_ascii,
    236         check_circular=check_circular, allow_nan=allow_nan, indent=indent,

TypeError: JSONEncoder.__init__() got an unexpected keyword argument 'orient'

```

### Expected behavior

GEOJson objects should be serialized with a string representation at the minimum

### Installed versions

<details>
```
/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
<frozen importlib._bootstrap>:914: ImportWarning: _PyDrive2ImportHook.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _PyDriveImportHook.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _GenerativeAIImportHook.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _OpenCVImportHook.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: APICoreClientInfoImportHook.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _BokehImportHook.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _AltairImportHook.find_spec() not found; falling back to find_module()

Selected Jupyter core packages...
executing in google-colab 
buckaroo         : 0.6.2
jupyterlab       : not installed
notebook         : 6.5.5
ipywidgets       : 7.7.1
traitlets        : 5.7.1
jupyter_core     : 5.7.1
pandas           : 1.5.3
numpy            : 1.25.2
IPython          : 7.34.0
ipykernel        : 5.5.6
jupyter_client   : 6.1.12
jupyter_server   : 1.24.0
nbclient         : 0.9.0
nbconvert        : 6.5.4
nbformat         : 5.9.2
qtconsole        : not installed
buckaroo         : /usr/local/lib/python3.10/dist-packages/buckaroo/__init__.py
jupyterlab       : not installed
notebook         : /usr/local/lib/python3.10/dist-packages/notebook/__init__.py
ipywidgets       : /usr/local/lib/python3.10/dist-packages/ipywidgets/__init__.py
traitlets        : /usr/local/lib/python3.10/dist-packages/traitlets/__init__.py
jupyter_core     : /usr/local/lib/python3.10/dist-packages/jupyter_core/__init__.py
pandas           : /usr/local/lib/python3.10/dist-packages/pandas/__init__.py
numpy            : /usr/local/lib/python3.10/dist-packages/numpy/__init__.py
IPython          : /usr/local/lib/python3.10/dist-packages/IPython/__init__.py
ipykernel        : /usr/local/lib/python3.10/dist-packages/ipykernel/__init__.py
jupyter_client   : /usr/local/lib/python3.10/dist-packages/jupyter_client/__init__.py
jupyter_server   : /usr/local/lib/python3.10/dist-packages/jupyter_server/__init__.py
nbclient         : /usr/local/lib/python3.10/dist-packages/nbclient/__init__.py
nbconvert        : /usr/local/lib/python3.10/dist-packages/nbconvert/__init__.py
nbformat         : /usr/local/lib/python3.10/dist-packages/nbformat/__init__.py
qtconsole        : not installed

```
</details>

**Comment by paddymul** [comment]
I think this is actually a geopandas bug.  https://github.com/geopandas/geopandas/issues/3187 I will wait to see their response,  I think there are ways to get around this without requiring a commit from geopandas.

**Comment by chbrandt** [comment]
If I were to dig in Buckaroo's code to try to work out a solution/workaround for the crash, where should I look into? 

As a first step, I would try to exclude from Buckaroo widget the "geometry" column, does that make sense?

**Comment by paddymul** [comment]
Normal dataframes are serialized like this:
```pd.DataFrame({'a':[10,20,30], 'b':["foo", "bar", None}})
df.to_json(orient='records')
```
yields
```
[{"a":10,"b":"foo"},
{"a":20,"b":"bar"},
{"a":30,"b":null}]
```

Can you write a method that takes a GeoPandas dataframe and returns similar rows.  Encode GeoPoints as embedded objects or tuples.  I will write an output format in the next comment.

**Comment by paddymul** [comment]
so the following abbreviated geopandas dataframe should serialize like this
```python
abbrev_geo_obj = {
    "type": "FeatureCollection",
    "features": [
        {
            "id": "0",
            "type": "Feature",
            "properties": {
                "sovereignt": "Ethiopia"},
            "geometry": {
                "type": "Polygon",
                "coordinates": [
                    [
                        [ 47.78, 8.00],
                        [ 44.96, 5.00],
                        [ 43.66, 4.95],
                        [ 46.94, 7.99],
                        [ 47.78, 8.00]]]}},
        {
            "id": "1",
            "type": "Feature",
            "properties": {
                "sovereignt": "South Sudan"},
            "geometry": {
                "type": "Polygon",
                "coordinates": [
                    [
                        [ 30.83, 3.50],
                        [ 29.95, 4.17],
                        [ 29.71, 4.60],
                        [ 29.15, 4.38],
                        [ 30.83, 3.50]]]}},
        {
            "id": "2",
            "type": "Feature",
            "properties": {
                "sovereignt": "Somalia"},
            "geometry": {
                "type": "Polygon",
                "coordinates": [
                    [
                        [ 41.58, -1.68],
                        [ 40.93, -0.85],
                        [ 40.95,  2.78],
                        [ 41.85,  3.91],
                        [ 42.13,  4.23],
                        [ 41.58, -1.68]]]}}]}
abbrev_df = geopandas.GeoDataFrame.from_features(abbrev_geo_obj)
```

```
[
    {"id": "0", "sovereignt": "Ethiopia", "geometry":[
        [ 47.78, 8.00],
        [ 44.96, 5.00],
        [ 43.66, 4.95],
        [ 46.94, 7.99],
        [ 47.78, 8.00]]},
    {"id": "0", "sovereignt": "South Sudan",
      "geometry":  [
          [ 30.83, 3.50],
          [ 29.95, 4.17],
          [ 29.71, 4.60],
          [ 29.15, 4.38],
          [ 30.83, 3.50]]},
    {"id": "0", "sovereignt": "Somalia"
      "geometry": [
          [ 41.58, -1.68],
          [ 40.93, -0.85],
          [ 40.95,  2.78],
          [ 41.85,  3.91],
          [ 42.13,  4.23],
          [ 41.58, -1.68]]}]

```

@chbrandt  can you write a function that does that serialization?

Also if a column is `dtype` `geometry` are all values of the same geometry type? are they all `polygon` or `point`.

If the type of values can vary, that needs to be encoded in the serialization

**Comment by paddymul** [comment]
Buckaroo will use the serialization to power special displayers that operate on `polygon` or `point`

Issues describe some base displayers:
 InlineMapDisplayer #212 
 Add googlemaps link displayer #211 


If you write the serialization, I can do the googlemaps link displayer.  Let's talk about an MVP for InlineMapDisplayer

**Comment by paddymul** [comment]
I just did some digging into GeoPandas.  If you could make a serialization/transformation that returns the actual objects, I can easily call `obj._repr_svg_` on them.  I just need to make an SVGDisplayer, which should be straightforward.

Check out this screenshot:
<img width="730" alt="Screenshot 2024-03-07 at 10 36 20 AM" src="https://github.com/paddymul/buckaroo/assets/40453/a6b6fa0f-9559-4f10-b7d5-591e52e8d960">

**Comment by chbrandt** [comment]
Nice! I don't know if it's still useful to your at this point, @paddymul , but I created this notebook with two different ways to serialize GeoDataFrame (Polygon objects):
- https://colab.research.google.com/drive/1E90frUGUx6Yj1F91Mycu272pYXpYyXc6?usp=sharing

In short, the (apparently) fastest method:

```python
def serialize_to_dict(gdf):
  """
  Serialize GeoDataFrame
  """
  import numpy

  # Let's work with 'index' output structure, it's closer to what we want
  dct = gdf.to_dict(orient='index')

  items = []
  for indx, fields in dct.items():
    # Create feature, with "id" value from GDF index
    item = { 'id': indx }

    # Transform 'geometry' object into list of coordinates
    geom = fields.pop('geometry')
    # Shapely interface to extract coordinates is... not uniform
    # For simplicity, implement it for Polygons and later for other objects...
    if geom.geom_type != 'Polygon':
      raise NotImplementedError
    geom = numpy.array(geom.exterior.coords.xy).T.tolist()
    item['geometry'] = geom

    # Add all the remaining fields to output feature/item
    item.update(fields)
    items.append(item)

  return items
```

Would give us what you requested above:

```python
[{'id': 0,
  'geometry': [[47.78, 8.0],
   [44.96, 5.0],
   [43.66, 4.95],
   [46.94, 7.99],
   [47.78, 8.0]],
  'sovereignt': 'Ethiopia'},
 {'id': 1,
  'geometry': [[30.83, 3.5],
   [29.95, 4.17],
   [29.71, 4.6],
   [29.15, 4.38],
   [30.83, 3.5]],
  'sovereignt': 'South Sudan'},
 {'id': 2,
  'geometry': [[41.58, -1.68],
   [40.93, -0.85],
   [40.95, 2.78],
   [41.85, 3.91],
   [42.13, 4.23],
   [41.58, -1.68]],
  'sovereignt': 'Somalia'}]
```

**Comment by chbrandt** [comment]
> Also if a column is `dtype` `geometry` are all values of the same geometry type? are they all `polygon` or `point`.
> 
> If the type of values can vary, that needs to be encoded in the serialization

Values can vary. There are no restrictions for homogeneity in `geometry`. 
If the (prototype) above works for you, I'll implement serialization for:

- [x] Polygon
- [ ] LineString
- [ ] Point
- [x] MultiPolygon
- [ ] MultiLineString
- [ ] MultiPoint

**Comment by paddymul** [comment]
Thank you for the sample code.  That will work well for a renderer that deals with the actual data.  For the initial geopandas release, I'm using `shapely._repr_svg_()` to get an svg representation of each geometry.  I expect `_repr_svg_` to have perfromance problems for large dataframes.


A couple of questions:
1. How is geopandas used?  How big are the dataframes that most users manipulate?
2. What types of transforms and aggregations do users generally want to perform on a GeoPandas Dataframe?

**Comment by paddymul** [comment]
I played around a bit with this, and added this extra support for `MultiPolygon`

```
def serialize_geom(geom):
    # Shapely interface to extract coordinates is... not uniform
    # For simplicity, implement it for Polygons and later for other objects...
    if geom.geom_type == 'Polygon':
      return numpy.array(geom.exterior.coords.xy).T.tolist()
    elif geom.geom_type == 'MultiPolygon':
      return [serialize_geom(g) for g in geom.geoms]
    else:
      raise NotImplementedError("No serialization for %s" % self.geom_type)

def serialize_to_dict(gdf):
  """
  Serialize GeoDataFrame
  """
  import numpy

  # Let's work with 'index' output structure, it's closer to what we want
  dct = gdf.to_dict(orient='index')

  items = []
  for indx, fields in dct.items():
    # Create feature, with "id" value from GDF index
    item = { 'id': indx }

    # Transform 'geometry' object into list of coordinates
    geom = fields.pop('geometry')
    item['geometry'] = serialize_geom(geom)

    # Add all the remaining fields to output feature/item
    item.update(fields)
    items.append(item)

  return items
```

The serialization method you have is already faster than basic `to_json()`, but I think there is a probably a lot of perfromance available since we are doing raw python operations here.

I don't know how much that matters though until I understand how GeoPandas is generally used.

**Comment by chbrandt** [comment]
I use small datasets since I am/was in the planetary science sub-group, but from my discussions and experiments with Earth data (eg, the map of a city) those datasets reach hundreds of thousands entries quite easily in an exploratory stage.

Here for example I read the vector data (shapefile) from the city of Bremen, Germany. This is a small city, with almost 200K polygons:
- https://colab.research.google.com/drive/1rlMTpVNGuh_AN3Ah4tsKNEMtKrD9lX0i?usp=sharing

Users will do a lot buffer, intersection, and unions operations; think of spatial *joins*. Apart from extracting *area* (from polygons) and *length* (from lines) measurements.

**Comment by paddymul** [comment]
This serialization bug no longer happens.  I will open a new feature request for  [Vector serialization of Geopandas data](https://github.com/paddymul/buckaroo/issues/251).  

@chbrandt I'm going to close this bug for now.  Thank you for your help and prompting about geopandas.  it led to some nice improvements that are just the start.
