### ISSUE TITLE
Histograms display without fills intermittently

### ISSUE THREAD

**Issue by paddymul** [buckaroo-data/buckaroo#292]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/paddymul/buckaroo) of Buckaroo.

### What type of jupyter notebook were you using (VSCode notebook, google colab, Jupyter Lab, Jupyter notebook).  Select multiple if you can reproduce this in multiple environments.  If other, please add to description.

Jupyter Lab

### Reproducible example

On example-notebooks/Full-tour.ipynb
The second dataframe initially has filled columns for unique and NA.  the third dataframe doesn't

<img width="666" alt="Screenshot 2024-10-11 at 10 47 53 AM" src="https://github.com/user-attachments/assets/9f42db2c-136f-4a28-8274-824d41654fc3">

On initial add of the third dataframe, the fill is empty

<img width="763" alt="Screenshot 2024-10-11 at 10 49 36 AM" src="https://github.com/user-attachments/assets/099b626a-f0fe-41e6-b074-9e1d98a6bf78">
Then when scrolling up to the first dataframe, you can see the fill, but scrolling left to right, the fills aren't re-rendered.

### Issue description

I think this is related to an interaction between re-charts and ag-grid.  Possibly some ID's embedded into the SVG rendering

### Expected behavior

histogram bars should always be rendered

### Installed versions

<details>
```
Run on 0.7.4
```
</details>

**Comment by nasrin1748** [comment]
It show's exactly as required with rendered fill. 
![Screenshot 2024-10-14 065515](https://github.com/user-attachments/assets/2ee21dba-5478-4455-aa05-440b88723fa0)

**Comment by paddymul** [comment]
Extensive deep dives 
https://github.com/recharts/recharts/issues/5230
and
https://github.com/jupyterlab/jupyterlab/issues/16952

unique ID fix coming soon
