### ISSUE TITLE
Polars read_parquet doesn't show buckaroo rendered dataframe.

### ISSUE THREAD

**Issue by ghost** [buckaroo-data/buckaroo#296]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/paddymul/buckaroo) of Buckaroo.

### What type of jupyter notebook were you using (VSCode notebook, google colab, Jupyter Lab, Jupyter notebook).  Select multiple if you can reproduce this in multiple environments.  If other, please add to description.

Jupyter Notebook

### Reproducible example

```python
import polars as pl
import buckaroo
df = pl.read_parquet("https://github.com/paddymul/buckaroo-data/raw/main/cb_data/2016-04.parq")
df
```

### Issue description

I am able to read parquet file using polars but it does not display buckaroo rendered dataframe.
![Screenshot 2024-10-14 071704](https://github.com/user-attachments/assets/219a4e1a-a793-4af5-b7cc-a7775d961b48)

### Expected behavior

Should display  buckaroo rendered dataframe.

### Installed versions

<details>
```
Selected Jupyter core packages...
executing in jupyter-notebook 
buckaroo         : 0.7.4
jupyterlab       : 4.2.5
notebook         : 7.0.8
ipywidgets       : 8.1.2
traitlets        : 5.7.1
jupyter_core     : 5.5.0
pandas           : 2.2.1
numpy            : 1.26.4
IPython          : 8.20.0
ipykernel        : 6.28.0
jupyter_client   : 8.6.0
jupyter_server   : 2.10.0
nbclient         : 0.8.0
nbconvert        : 7.10.0
nbformat         : 5.9.2
qtconsole        : not installed
buckaroo         : C:\Users\91949\anaconda3\new\envs\new1\Lib\site-packages\buckaroo\__init__.py
jupyterlab       : C:\Users\91949\anaconda3\new\envs\new1\Lib\site-packages\jupyterlab\__init__.py
notebook         : C:\Users\91949\anaconda3\new\envs\new1\Lib\site-packages\notebook\__init__.py
ipywidgets       : C:\Users\91949\anaconda3\new\envs\new1\Lib\site-packages\ipywidgets\__init__.py
traitlets        : C:\Users\91949\anaconda3\new\envs\new1\Lib\site-packages\traitlets\__init__.py
jupyter_core     : C:\Users\91949\anaconda3\new\envs\new1\Lib\site-packages\jupyter_core\__init__.py
pandas           : C:\Users\91949\anaconda3\new\envs\new1\Lib\site-packages\pandas\__init__.py
numpy            : C:\Users\91949\anaconda3\new\envs\new1\Lib\site-packages\numpy\__init__.py
IPython          : C:\Users\91949\anaconda3\new\envs\new1\Lib\site-packages\IPython\__init__.py
ipykernel        : C:\Users\91949\anaconda3\new\envs\new1\Lib\site-packages\ipykernel\__init__.py
jupyter_client   : C:\Users\91949\anaconda3\new\envs\new1\Lib\site-packages\jupyter_client\__init__.py
jupyter_server   : C:\Users\91949\anaconda3\new\envs\new1\Lib\site-packages\jupyter_server\__init__.py
nbclient         : C:\Users\91949\anaconda3\new\envs\new1\Lib\site-packages\nbclient\__init__.py
nbconvert        : C:\Users\91949\anaconda3\new\envs\new1\Lib\site-packages\nbconvert\__init__.py
nbformat         : C:\Users\91949\anaconda3\new\envs\new1\Lib\site-packages\nbformat\__init__.py
qtconsole        : not installed
```
</details>

**Comment by paddymul** [comment]
I just tried this on google colab, and it works.

<img width="1165" alt="Screenshot 2024-10-14 at 9 41 16 AM" src="https://github.com/user-attachments/assets/ac1a5ba0-9cd9-46df-b18f-2c53088d8d20">

Can you please follow the instructions with `buckaroo.debug_packages()` so I can properly debug the problem you are running into.

For now I am closing this as can't reproduce.  With more info I can re-open it.

**Comment by ghost** [comment]
I tried in google colab as well but buckaroo rendering is not shown.
![Screenshot 2024-10-15 052827](https://github.com/user-attachments/assets/40b10a68-955c-4801-97cf-ec720d72dc50)

**Comment by paddymul** [comment]
You're calling `print(df)`.  which prints it to text

**Comment by ghost** [comment]
I just tried print(df) becz df was showing blank.Indeed the query got solved after running the following code.         
 ```
 from google.colab import output
output.enable_custom_widget_manager()
```
