### ISSUE TITLE
Undo default capitalization of column names?

### ISSUE THREAD

**Issue by matthew-brett** [buckaroo-data/buckaroo#43]
Thanks for this very nice-looking tool.

I noticed that the UI capitalizes my column names, at least by default.  This is inconvenient, because I have to then separately check what the capitalization is for the columns, before using the names from the display.   Is there any way to disable changing case of the column names by default?

Thanks again.

**Comment by paddymul** [comment]
Thank you for flagging this.  I have been aware of the problem, I'll take a look at a fix today.

**Comment by matthew-brett** [comment]
Great - thanks for your fast reply.
