### ISSUE TITLE
Text row labels appear blank

### ISSUE THREAD

**Issue by matthew-brett** [buckaroo-data/buckaroo#44]
Thanks again - enjoying the exploration so far.

I have noticed that when I use text labels for the Pandas index, these appear blank - is this just me?  For example:

```python
import buckaroo
import pandas as pd

df = pd.DataFrame(
    dict(names=['one', 'two', 'three'],
         values=[1, 2, 3])).set_index('names')
df
```

For me at least the row labels are blank for these text labels, but leaving the default number labels, these appear correctly.

**Comment by paddymul** [comment]
Indeed I see the same thing.  Let me do some digging.

<img width="493" alt="Screen Shot 2023-10-17 at 9 47 01 AM" src="https://github.com/paddymul/buckaroo/assets/40453/dba54b9b-16b4-458c-97ba-1d73b714be2e">


Keep the bugs coming, this is great feedback

**Comment by ghost** [comment]
Adding set_index is displaying the Values header not in correct place.
<img width="344" alt="23" src="https://github.com/paddymul/buckaroo/assets/79505893/d19429c8-a0f4-4fba-b62a-1d1f157dd020">
Removing set_index is displaying the header in correct place.
<img width="284" alt="24" src="https://github.com/paddymul/buckaroo/assets/79505893/36fe5a5b-8f7c-4b06-87ae-4abb88f73f41">
