### ISSUE TITLE
Add Red/Black conditional formatting

### ISSUE THREAD

**Issue by paddymul** [buckaroo-data/buckaroo#58]
Add conditional formatting that shows negative numbers in red, positive in black

**Comment by georgioupanayiotis** [comment]
@paddymul can you please assign this

**Comment by paddymul** [comment]
@georgioupanayiotis Were you asking for this to be assigned to you?  What are your thoughts about implementing this feature?

**Comment by paddymul** [comment]
Look at https://github.com/paddymul/buckaroo/blob/main/example-notebooks/styling-gallery.ipynb

Fixed by https://github.com/paddymul/buckaroo/pull/201 for release 0.6.1
