### ISSUE TITLE
Widget styles not rendered properly in VS Code

### ISSUE THREAD

**Issue by rebornix** [buckaroo-data/buckaroo#61]
Thanks for this great package, it's very promising. I played around with it in VS Code but found the widget is not rendered properly. It might be because it's assuming the widget is rendered in Jupyter Lab context and using some Jupyter Lab css rules, which don't exist in VS Code output webview
 
![Image](https://github.com/paddymul/buckaroo/assets/876920/43f00200-4f8c-4c03-9cde-689e2020d7a0)

**Comment by paddymul** [comment]
Are you talking about the low-code UI on the botton?  `dropcol`, `safeint`...`to_string`?

The Low Code UI was one of the first parts of buckaroo that I built, and it's that ugly in Jupyter too :) 

Look at this bug report for more details 
https://github.com/paddymul/buckaroo/issues/63
<img width="827" alt="Screen Shot 2023-10-20 at 9 18 24 AM" src="https://github.com/paddymul/buckaroo/assets/40453/326c4846-b7fe-436c-af6f-cc95c83dca06">

**Comment by rebornix** [comment]
@paddymul you are right, somehow I thought it was oversight ;) Closing this issue now.
