### ISSUE TITLE
More than one space is considered as  0

### ISSUE THREAD

**Issue by ghost** [buckaroo-data/buckaroo#70]
Column value with no space is considered as NULL.But column value with more than one space is considered as zero.It was suppose to be considered as NULL.
<img width="477" alt="31" src="https://github.com/paddymul/buckaroo/assets/79505893/ae313697-ba9c-4b34-b1c7-86ee0b8791d9">

**Comment by paddymul** [comment]
This is due to the auto-cleaning behaviour.  I need to document that functionality.

Here is what's happening
the autocleaing is determining that `pairs` is an integer column and `' '` doesn't convert to an integer properly, therefore it is replaced with `NA`.

for now you can use
`BuckarooWidget(df, autoType=False)` which will turn off autoTyping.
You can also open the lowcode UI under the `λ` menu and delete the operation for `pairs`.


AutoCleaning is set up quite aggresively.  Eventually I want to let users toggle through multiple autoCleaning methods, including `off`.

**Comment by paddymul** [comment]
@nasrin1748 Can you please look me up and contact me offline for a screenshare.  I'm glad you're actively using the library and I'd like to review some things with you.

**Comment by ghost** [comment]
contact me offline for a screenshare?Sorry I did't get you?

**Comment by ghost** [comment]
I think you misunderstood my question.He's what i am trying to say.I think it's no where related to auto-cleaning.
<img width="467" alt="32" src="https://github.com/paddymul/buckaroo/assets/79505893/7c97b475-a8ff-4805-a2a7-541cf5b4f5e5">
<img width="357" alt="33" src="https://github.com/paddymul/buckaroo/assets/79505893/abe96446-cd6c-4337-b86e-f55d7e76bbe4">
The second image should take the value as NA i think not 0.

**Comment by paddymul** [comment]
I just added docs about auto_typing https://buckaroo-data.readthedocs.io/en/latest/articles/auto_clean.html

**Comment by paddymul** [comment]
Oh, that is indeed unexpected.  I will take a look

> I think you misunderstood my question.He's what i am trying to say.I think it's no where related to auto-cleaning. <img alt="32" width="467" src="https://user-images.githubusercontent.com/79505893/277445719-7c97b475-a8ff-4805-a2a7-541cf5b4f5e5.png"> <img alt="33" width="357" src="https://user-images.githubusercontent.com/79505893/277446298-abe96446-cd6c-4337-b86e-f55d7e76bbe4.png"> The second image should take the value as NA i think not 0.

**Comment by ghost** [comment]
Probably we need to use trim() so it will trim multiple spaces as single space and it will consider the value as NA

**Comment by paddymul** [comment]
this looks like a problem with `anyFormatter` in `gridUtils.ts`. it is trying to format the value as a number, somehow succeeding, then returning the value as a number to the table for display

**Comment by ghost** [comment]
How about this??
<img width="317" alt="45" src="https://github.com/paddymul/buckaroo/assets/79505893/713beede-59a3-4858-928f-8a5a2cbdda44">
