### ISSUE TITLE
Dragging makes the elements disappear.

### ISSUE THREAD

**Issue by ghost** [buckaroo-data/buckaroo#85]
<img width="410" alt="21" src="https://github.com/paddymul/buckaroo/assets/79505893/e5928eb6-8f6d-4d20-841c-4b758e8d7dd0">

**Comment by paddymul** [comment]
What did you drag?  How can I reproduce this bug?

**Comment by ghost** [comment]
https://www.youtube.com/watch?v=lFtI2TlwPG4

**Comment by paddymul** [comment]
Ahh, I see.  Yes that is possible.  I don't recommend users do that.  It doesn't seem like a bug that would be encountered through regular use of the table.  I won't be fixing this.  If users regularly complain about this, we can reopen the issue.

The drag and drop functionality comes from AG-Grid.  I would expect the default behavior to be that the columns snap back to their original position.
