### ISSUE TITLE
<img width="461" alt="20" src="https://github.com/paddymul/buckaroo/assets/79505893/44730f4f-d372-4dbe-89eb-9daeae92fdb0">

### ISSUE THREAD

**Issue by ghost** [buckaroo-data/buckaroo#86]
<img width="461" alt="20" src="https://github.com/paddymul/buckaroo/assets/79505893/44730f4f-d372-4dbe-89eb-9daeae92fdb0">

import pandas as pd
df1 = pd.DataFrame(
    dict(Names=[1,2,'one','two',3]))
df1

import pandas as pd
df1 = pd.DataFrame(
    dict(Names=[1,2,'one','two',3,4,'six']))
df1
The following codes shows NA for me.

_Originally posted by @nasrin1748 in https://github.com/paddymul/buckaroo/issues/77#issuecomment-1781293223_

**Comment by ghost** [comment]
pandas dataframe displays strings as blank but Buckroowidget displays is correctly.
<img width="527" alt="1" src="https://github.com/paddymul/buckaroo/assets/79505893/a0ef8dcb-b72e-4ab6-803b-991b3af9bdd9">
<img width="468" alt="2" src="https://github.com/paddymul/buckaroo/assets/79505893/93be1805-416b-4dcc-a24c-d7832ea90b0e">

**Comment by paddymul** [comment]
This works as designed via auto cleaning.  Whether or not autocleaning behavior is a surprise remains to be seen
