### ISSUE TITLE
Turn off auto-cleaning by default

### ISSUE THREAD

**Issue by paddymul** [buckaroo-data/buckaroo#93]
Good advice was given that by default buckaroo should do the least surprising thing.  This makes sense.

Two possible options exist for how to enable auto cleaning:

```
from buckaroo import auto_clean_widget
```
which would enable the auto cleaning
or
```
import buckaroo
buckaroo.enable_autoclean()
```

I could do both and have `buckaroo.auto_clean_widget` just call `buckaroo.enable_autoclean`.

I also like the idea of 
```
class MyAnalysis(ColAnalysis): pass
buckaroo.enable_customized(MyAnalysis)
```
as a  standard way of customizing the default buckaroo renderer

```

**Comment by jqmp** [comment]
FWIW, I think my vote would be making all global effects opt-in, like this:
```
import buckaroo
...
buckaroo.enable(widget=True, autoclean=True, analysis=MyAnalysis)
```
I also like how this lets you do all your configuration in one call, whereas `from buckaroo import auto_clean_widget` can only do one thing, and can't take any arguments. (Also it still strikes me as a bit surprising that just doing the import would have a global side effect.)

**Comment by paddymul** [comment]
I really like that enable syntax that mimics invoking `BuckarooWidget`

**Comment by paddymul** [comment]
I think I'm going to leave `import `buckaroo` to turn on Buckaroo rendering for all DataFrames.  I will change the defaults to turn off autoCleaning.
 
Importing buckaroo to enable table rendering is the most common usecase by a large margin.
There is also `buckaroo.disable()` to turn off rendering.  

I also added this issue for explicit pandas rendering. https://github.com/paddymul/buckaroo/issues/96
